# Generated by Django 5.1.2 on 2024-10-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('acno', models.IntegerField(max_length=16, primary_key='acno', serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('collateral', models.CharField(max_length=3)),
                ('occupation', models.CharField(max_length=20)),
                ('loanid', models.IntegerField(max_length=15)),
            ],
        ),
    ]
