# Generated by Django 5.1.2 on 2024-10-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='acno',
            field=models.IntegerField(primary_key='acno', serialize=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loanid',
            field=models.IntegerField(),
        ),
    ]
